#ifndef __LIB_ERROR_CODE_H
#define __LIB_ERROR_CODE_H

#include<kit/types.h>
#include<kit/bit.h>


typedef Uint32 ErrorCode;


#define ERROR_CODE_SHIFT      0
#define ERROR_CODE_MASK       MASK_RANGE(32, ERROR_CODE_SHIFT, ERROR_SUBDOMAIN_SHIFT)

#define ERROR_SUBDOMAIN_SHIFT 6
#define ERROR_SUBDOMAIN_MASK  MASK_RANGE(32, ERROR_SUBDOMAIN_SHIFT, ERROR_SEVERITY_SHIFT)

#define ERROR_SEVERITY_SHIFT  12
#define ERROR_SEVERITY_MASK   MASK_RANGE(32, ERROR_SEVERITY_SHIFT, ERROR_CLASS_SHIFT)

#define ERROR_CLASS_SHIFT     16
#define ERROR_CLASS_MASK      MASK_RANGE(32, ERROR_CLASS_SHIFT, ERROR_DOMAIN_SHIFT)

#define ERROR_DOMAIN_SHIFT    24
#define ERROR_DOMAIN_MASK     MASK_RANGE(32, ERROR_DOMAIN_SHIFT, 32)

#define ERROR_MAKE(__DOMAIN, __CLASS, __SEVERITY, __SUBDOMAIN, __CODE)  \
    VAL_LEFT_SHIFT(__DOMAIN, ERROR_DOMAIN_SHIFT)        |   \
    VAL_LEFT_SHIFT(__CLASS, ERROR_CLASS_SHIFT)          |   \
    VAL_LEFT_SHIFT(__SEVERITY, ERROR_SEVERITY_SHIFT)    |   \
    VAL_LEFT_SHIFT(__SUBDOMAIN, ERROR_SUBDOMAIN_SHIFT)  |   \
    VAL_LEFT_SHIFT(__CODE, ERROR_CODE_SHIFT)

#define ERROR_GET_CODE(__ERR)       EXTRACT_VAL(__ERR, 32, ERROR_CODE_SHIFT, ERROR_SUBDOMAIN_SHIFT)
#define ERROR_GET_SUBDOMAIN(__ERR)  EXTRACT_VAL(__ERR, 32, ERROR_SUBDOMAIN_SHIFT, ERROR_SEVERITY_SHIFT)
#define ERROR_GET_SEVERITY(__ERR)   EXTRACT_VAL(__ERR, 32, ERROR_SEVERITY_SHIFT, ERROR_CLASS_SHIFT)
#define ERROR_GET_CLASS(__ERR)      EXTRACT_VAL(__ERR, 32, ERROR_CLASS_SHIFT, ERROR_DOMAIN_SHIFT)
#define ERROR_GET_DOMAIN(__ERR)     EXTRACT_VAL(__ERR, 32, ERROR_DOMAIN_SHIFT, 32)

#define ERROR_SEV_INFO          (0x0ULL << ERROR_SEVERITY_SHIFT)   // Informational
#define ERROR_SEV_WARNING       (0x1ULL << ERROR_SEVERITY_SHIFT)   // Warning
#define ERROR_SEV_ERROR         (0x2ULL << ERROR_SEVERITY_SHIFT)   // General error
#define ERROR_SEV_CRITICAL      (0x3ULL << ERROR_SEVERITY_SHIFT)   // Critical error
#define ERROR_SEV_FATAL         (0x4ULL << ERROR_SEVERITY_SHIFT)   // Fatal error (system-level)

#define ERROR_DOMAIN_GENERIC    0x00U   // Generic errors
#define ERROR_DOMAIN_MEMORY     0x01U   // Memory management
#define ERROR_DOMAIN_FS         0x02U   // File system
#define ERROR_DOMAIN_PROCESS    0x03U   // Process/thread
#define ERROR_DOMAIN_DEVICE     0x04U   // Device driver
#define ERROR_DOMAIN_NETWORK    0x05U   // Network
#define ERROR_DOMAIN_SYNC       0x06U   // Synchronization primitives
#define ERROR_DOMAIN_VIRT       0x07U   // Virtualization
#define ERROR_DOMAIN_USER       0x80U   // User-space errors
#define ERROR_DOMAIN_CUSTOM     0xFEU   // Custom domain
#define ERROR_DOMAIN_RESERVED   0xFFU   // Reserved

// Generic error classes
#define ERROR_CLASS_INVALID     0x01U   // Invalid parameter/state
#define ERROR_CLASS_NOTFOUND    0x02U   // Not found
#define ERROR_CLASS_EXISTS      0x03U   // Already exists
#define ERROR_CLASS_PERM        0x04U   // Permission denied
#define ERROR_CLASS_RESOURCE    0x05U   // Resource exhausted
#define ERROR_CLASS_IO          0x06U   // I/O error
#define ERROR_CLASS_TIMEOUT     0x07U   // Timeout (recoverable)
#define ERROR_CLASS_CANCEL      0x08U   // Operation cancelled (recoverable)
#define ERROR_CLASS_BUSY        0x09U   // Busy/locked (recoverable)
#define ERROR_CLASS_NOSUPPORT   0x0AU   // Not supported

#define ERROR_OK                    ERROR_MAKE(ERROR_DOMAIN_GENERIC, 0, ERROR_SEV_INFO, 0, 0)
#define ERROR_INVALID_ARGUMENT      ERROR_MAKE(ERROR_DOMAIN_GENERIC, ERROR_CLASS_INVALID, ERROR_SEV_ERROR, 0, 1)
#define ERROR_INVALID_STATE         ERROR_MAKE(ERROR_DOMAIN_GENERIC, ERROR_CLASS_INVALID, ERROR_SEV_ERROR, 0, 2)
#define ERROR_NOT_FOUND             ERROR_MAKE(ERROR_DOMAIN_GENERIC, ERROR_CLASS_NOTFOUND, ERROR_SEV_ERROR, 0, 3)
#define ERROR_ALREADY_EXISTS        ERROR_MAKE(ERROR_DOMAIN_GENERIC, ERROR_CLASS_EXISTS, ERROR_SEV_ERROR, 0, 4)
#define ERROR_PERMISSION_DENIED     ERROR_MAKE(ERROR_DOMAIN_GENERIC, ERROR_CLASS_PERM, ERROR_SEV_ERROR, 0, 5)
#define ERROR_OUT_OF_MEMORY         ERROR_MAKE(ERROR_DOMAIN_GENERIC, ERROR_CLASS_RESOURCE, ERROR_SEV_CRITICAL, 0, 6)
#define ERROR_OUT_OF_RESOURCES      ERROR_MAKE(ERROR_DOMAIN_GENERIC, ERROR_CLASS_RESOURCE, ERROR_SEV_ERROR, 0, 7)
#define ERROR_NOT_SUPPORTED         ERROR_MAKE(ERROR_DOMAIN_GENERIC, ERROR_CLASS_NOSUPPORT, ERROR_SEV_WARNING, 0, 8)
#define ERROR_OPERATION_CANCELLED   ERROR_MAKE(ERROR_DOMAIN_GENERIC, ERROR_CLASS_CANCEL, ERROR_SEV_INFO, 0, 9)
#define ERROR_TIMEOUT               ERROR_MAKE(ERROR_DOMAIN_GENERIC, ERROR_CLASS_TIMEOUT, ERROR_SEV_ERROR, 0, 10)
#define ERROR_BUSY                  ERROR_MAKE(ERROR_DOMAIN_GENERIC, ERROR_CLASS_BUSY, ERROR_SEV_WARNING, 0, 11)
#define ERROR_IO_FAILED             ERROR_MAKE(ERROR_DOMAIN_GENERIC, ERROR_CLASS_IO, ERROR_SEV_ERROR, 0, 12)

#define ERROR_SUBDOMAIN_FS_GENERIC  0x00U
#define ERROR_SUBDOMAIN_FS_EXT2     0x01U
#define ERROR_SUBDOMAIN_FS_FAT32    0x02U
#define ERROR_SUBDOMAIN_FS_DEVFS    0x03U

// // FS Errors
// #define ERROR_FS_NOT_MOUNTED        ERROR_MAKE(ERROR_DOMAIN_FS, ERROR_CLASS_NOTFOUND, ERROR_SEV_ERROR, ERROR_SUBDOMAIN_FS_GENERIC, 1)
// #define ERROR_FS_INVALID_PATH       ERROR_MAKE(ERROR_DOMAIN_FS, ERROR_CLASS_INVALID, ERROR_SEV_ERROR, ERROR_SUBDOMAIN_FS_GENERIC, 2)

// // EXT2 Specific Errors
// #define ERROR_EXT2_INODE_CORRUPT    ERROR_MAKE(ERROR_DOMAIN_FS, ERROR_CLASS_IO, ERROR_SEV_CRITICAL, ERROR_SUBDOMAIN_FS_EXT2, 1)

// // FAT32 Specific Errors  
// #define ERROR_FAT32_CLUSTER_CHAIN_BROKEN ERROR_MAKE(ERROR_DOMAIN_FS, ERROR_CLASS_IO, ERROR_SEV_CRITICAL, ERROR_SUBDOMAIN_FS_FAT32, 1)

#endif // __LIB_ERROR_CODE_H
