BUILD_BASE_DIR			:= $(RELATIVE_BASE)/build
BUILD_BOORLOADER_DIR	:= $(BUILD_BASE_DIR)/boot
BUILD_KERNEL_DIR		:= $(BUILD_BASE_DIR)/kernel

BUILD_TARGET_NAME		:= EGOS.img
BUILD_BOOTLOADER_NAME	:= bootloader.bin
BUILD_KERNEL_NAME		:= kernel.elf

BUILD_TARGET			:= $(BUILD_BASE_DIR)/$(BUILD_TARGET_NAME)
BUILD_BOOTLOADER		:= $(BUILD_BOORLOADER_DIR)/$(BUILD_BOOTLOADER_NAME)
BUILD_KERNEL			:= $(BUILD_KERNEL_DIR)/$(BUILD_KERNEL_NAME)

TARGET_SIZE_MB			:= 64

TMP_DIR					:= $(RELATIVE_BASE)/tmp
MOUNT_DIR				:= $(RELATIVE_BASE)/mount
FILES_DIR				:= $(RELATIVE_BASE)/files