#if !defined(__KIT_MACRO_H)
#define __KIT_MACRO_H

#define MACRO_RESCAN(__X) __X

#define MACRO_EXPRESSION(__X) (__X)

#define MACRO_STR(__X) #__X

#define MACRO_CONCENTRATE2(__A, __B) __A ## __B

#define MACRO_CONCENTRATE3(__A, __B, __C) __A ## __B ## __C

#define MACRO_CONCENTRATE4(__A, __B, __C, __D) __A ## __B ## __C ## __D

#define MACRO_CALL(__MACRO, ...) MACRO_RESCAN(__MACRO(__VA_ARGS__))

#define ___RESCAN_FACTOR ()

#define ___RESCAN_DUMMY1(__ARG) ___RESCAN_DUMMY2(___RESCAN_DUMMY2(___RESCAN_DUMMY2(___RESCAN_DUMMY2(__ARG))))

#define ___RESCAN_DUMMY2(__ARG) ___RESCAN_DUMMY3(___RESCAN_DUMMY3(___RESCAN_DUMMY3(___RESCAN_DUMMY3(__ARG))))

#define ___RESCAN_DUMMY3(__ARG) MACRO_RESCAN(MACRO_RESCAN(MACRO_RESCAN(MACRO_RESCAN(__ARG))))

#define MACRO_FOREACH_CALL(__MACRO, __CONNECTOR, ...) __VA_OPT__(___RESCAN_DUMMY1(__MACRO_FOREACH_CALL_HELPER(__MACRO, __CONNECTOR, __VA_ARGS__)))

#define __MACRO_FOREACH_CALL_HELPER(__MACRO, __CONNECTOR, __ARG1, ...) __MACRO(__ARG1) __VA_OPT__(__CONNECTOR __MACRO_FOREACH_CALL_RECURSIVE ___RESCAN_FACTOR (__MACRO, __CONNECTOR, __VA_ARGS__))

#define __MACRO_FOREACH_CALL_RECURSIVE()  __MACRO_FOREACH_CALL_HELPER

#define MACRO_COUNT(...)    __MACRO_COUNT_IMPL(__VA_ARGS__ __VA_OPT__(,) 7, 6, 5, 4, 3, 2, 1, 0)

#define __MACRO_COUNT_IMPL(__N7, __N6, __N5, __N4, __N3, __N2, __N1, __N0, ...)   __N0

#define MACRO_IF_EMPTY(__A, __B, __C) MACRO_CALL(MACRO_CONCENTRATE2, __MACRO_IF_EMPTY_, MACRO_COUNT(__A)) (__B, __C)

#define __MACRO_IF_EMPTY_0(__B, __C)  __C
#define __MACRO_IF_EMPTY_1(__B, __C)  __B

#endif // __KIT_MACRO_H