#if !defined(__MACRO_H)
#define __MACRO_H

#define MACRO_RESCAN(__X) __X

#define MACRO_EXPRESSION(__X) (__X)

#define MACRO_STR(__X) #__X

#define MACRO_CONCENTRATE2(__A, __B) __A ## __B

#define MACRO_CONCENTRATE3(__A, __B, __C) __A ## __B ## __C

#define MACRO_CONCENTRATE4(__A, __B, __C, __D) __A ## __B ## __C ## __D

#define MACRO_CALL(__MACRO, ...) MACRO_RESCAN(__MACRO(__VA_ARGS__))

#define ___RESCAN_FACTOR ()

#define ___RESCAN_DUMMY1(__ARG) ___RESCAN_DUMMY2(___RESCAN_DUMMY2(___RESCAN_DUMMY2(___RESCAN_DUMMY2(__ARG))))

#define ___RESCAN_DUMMY2(__ARG) ___RESCAN_DUMMY3(___RESCAN_DUMMY3(___RESCAN_DUMMY3(___RESCAN_DUMMY3(__ARG))))

#define ___RESCAN_DUMMY3(__ARG) MACRO_RESCAN(MACRO_RESCAN(MACRO_RESCAN(MACRO_RESCAN(__ARG))))

#define FOREACH_MACRO_CALL(__MACRO, __CONNECTOR, ...) __VA_OPT__(___RESCAN_DUMMY1(__FOREACH_MACRO_CALL_HELPER(__MACRO, __CONNECTOR, __VA_ARGS__)))

#define __FOREACH_MACRO_CALL_HELPER(__MACRO, __CONNECTOR, __ARG1, ...) __MACRO(__ARG1) __VA_OPT__(__CONNECTOR __FOREACH_MACRO_CALL_RECURSIVE ___RESCAN_FACTOR (__MACRO, __CONNECTOR, __VA_ARGS__))

#define __FOREACH_MACRO_CALL_RECURSIVE()  __FOREACH_MACRO_CALL_HELPER

#endif // __MACRO_H