#include<system/GDT.h>

__attribute__((aligned(16), section(".init.data"), used))
GDTEntry GDTable64[16] = {
    //In 64-bit mode, the processor DOES NOT perform runtime limit checking on code or data segments. However, the processor does check descriptor-table limits.
    //That's why we can jump to kernel starts at position far above segment's limitation
    //<<Intel® 64 and IA-32 Architectures Software Developer’s Manual>> 5.3.1
    [0]                             = 0,
    [GDT_ENTRY_INDEX_KERNEL_CODE]   = BUILD_GDT_ENTRY(0x00000000, 0xFFFFF, GDT_ACCESS | GDT_READABLE | GDT_EXECUTABLE | GDT_DESCRIPTOR | GDT_PRIVIEGE_0 | GDT_PRESENT, GDT_GRANULARITY | GDT_LONG_MODE),
    [GDT_ENTRY_INDEX_KERNEL_DATA]   = BUILD_GDT_ENTRY(0x00000000, 0xFFFFF, GDT_ACCESS | GDT_READABLE_AND_WRITABLE | GDT_DESCRIPTOR | GDT_PRIVIEGE_0 | GDT_PRESENT, GDT_GRANULARITY | GDT_LONG_MODE),
    [GDT_ENTRY_INDEX_USER_CODE32]   = BUILD_GDT_ENTRY(0x00000000, 0xFFFFF, GDT_ACCESS | GDT_READABLE | GDT_EXECUTABLE | GDT_DESCRIPTOR | GDT_PRIVIEGE_3 | GDT_PRESENT, GDT_GRANULARITY | GDT_SIZE),
    [GDT_ENTRY_INDEX_USER_DATA]     = BUILD_GDT_ENTRY(0x00000000, 0xFFFFF, GDT_ACCESS | GDT_READABLE_AND_WRITABLE | GDT_DESCRIPTOR | GDT_PRIVIEGE_3 | GDT_PRESENT, GDT_GRANULARITY | GDT_LONG_MODE),
    [GDT_ENTRY_INDEX_USER_CODE]     = BUILD_GDT_ENTRY(0x00000000, 0xFFFFF, GDT_ACCESS | GDT_READABLE | GDT_EXECUTABLE | GDT_DESCRIPTOR | GDT_PRIVIEGE_3 | GDT_PRESENT, GDT_GRANULARITY | GDT_LONG_MODE)
};