#if !defined(__REAL_PORTS_PCI_H)
#define __REAL_PORTS_PCI_H

#include<kit/bit.h>
#include<kit/types.h>

#define PCI_CONFIG_ADDR 0xCF8
#define PCI_CONFIG_DATA 0xCFC

//In bits
#define PCI_CONFIG_ADDR_REGISTER_NUMBER_BEGIN               2
#define PCI_CONFIG_ADDR_REGISTER_NUMBER_LENGTH              6
#define PCI_CONFIG_ADDR_REGISTER_OFFSET_TO_NUMBER(__OFFSET) CLEAR_VAL_SIMPLE(__OFFSET, 8, PCI_CONFIG_ADDR_REGISTER_NUMBER_BEGIN)

#define PCI_CONFIG_ADDR_FUNCTION_NUMBER_BEGIN               8
#define PCI_CONFIG_ADDR_FUNCTION_NUMBER_LENGTH              3

#define PCI_CONFIG_ADDR_DEVICE_NUMBER_BEGIN                 11
#define PCI_CONFIG_ADDR_DEVICE_NUMBER_LENGTH                5

#define PCI_CONFIG_ADDR_BUS_NUMBER_BEGIN                    16
#define PCI_CONFIG_ADDR_BUS_NUMBER_LENGTH                   8

#define PCI_CONFIG_ADDR_ENABLE                              FLAG32(31)

static inline Uint32 pci_buildAddr(Uint8 bus, Uint8 device, Uint8 func, Uint8 reg) {
    reg = TRIM_VAL_SIMPLE(reg, 8, PCI_CONFIG_ADDR_REGISTER_NUMBER_LENGTH);
    func = TRIM_VAL_SIMPLE(func, 8, PCI_CONFIG_ADDR_FUNCTION_NUMBER_LENGTH);
    device = TRIM_VAL_SIMPLE(device, 8, PCI_CONFIG_ADDR_DEVICE_NUMBER_LENGTH);
    return  VAL_LEFT_SHIFT((Uint32)reg, PCI_CONFIG_ADDR_REGISTER_NUMBER_BEGIN) |
            VAL_LEFT_SHIFT((Uint32)func, PCI_CONFIG_ADDR_FUNCTION_NUMBER_BEGIN) |
            VAL_LEFT_SHIFT((Uint32)device, PCI_CONFIG_ADDR_DEVICE_NUMBER_BEGIN) |
            VAL_LEFT_SHIFT((Uint32)bus, PCI_CONFIG_ADDR_BUS_NUMBER_BEGIN);
}

#define PCI_REGISTER_NUMBER_FROM_ADDR(__ADDR)   EXTRACT_VAL(__ADDR, 32, PCI_CONFIG_ADDR_REGISTER_NUMBER_BEGIN, PCI_CONFIG_ADDR_REGISTER_NUMBER_BEGIN + PCI_CONFIG_ADDR_REGISTER_NUMBER_LENGTH)
#define PCI_FUNCTION_NUMBER_FROM_ADDR(__ADDR)   EXTRACT_VAL(__ADDR, 32, PCI_CONFIG_ADDR_FUNCTION_NUMBER_BEGIN, PCI_CONFIG_ADDR_FUNCTION_NUMBER_BEGIN + PCI_CONFIG_ADDR_FUNCTION_NUMBER_LENGTH)
#define PCI_DEVICE_NUMBER_FROM_ADDR(__ADDR)     EXTRACT_VAL(__ADDR, 32, PCI_CONFIG_ADDR_DEVICE_NUMBER_BEGIN, PCI_CONFIG_ADDR_DEVICE_NUMBER_BEGIN + PCI_CONFIG_ADDR_DEVICE_NUMBER_LENGTH)
#define PCI_BUS_NUMBER_FROM_ADDR(__ADDR)        EXTRACT_VAL(__ADDR, 32, PCI_CONFIG_ADDR_BUS_NUMBER_BEGIN, PCI_CONFIG_ADDR_BUS_NUMBER_BEGIN + PCI_CONFIG_ADDR_BUS_NUMBER_LENGTH)

#endif // __REAL_PORTS_PCI_H
