#if !defined(__BITS_H)
#define __BITS_H

#include<lib/macro.h>
#include<stdint.h>

#define BITS_LOGIC_EQUAL(X, Y)          (MACRO_EXPRESSION(X) == MACRO_EXPRESSION(Y))
#define BITS_LOGIC_NOT_EQUAL(X, Y)      (MACRO_EXPRESSION(X) != MACRO_EXPRESSION(Y))
#define BITS_LOGIC_AND(X, Y)            (MACRO_EXPRESSION(X) && MACRO_EXPRESSION(Y))
#define BITS_LOGIC_OR(X, Y)             (MACRO_EXPRESSION(X) || MACRO_EXPRESSION(Y))
#define BITS_LOGIC_NOT(X)               (!MACRO_EXPRESSION(X))

#define BITS_AND(X, Y)                  (MACRO_EXPRESSION(X) & MACRO_EXPRESSION(Y))
#define BITS_OR(X, Y)                   (MACRO_EXPRESSION(X) | MACRO_EXPRESSION(Y))
#define BITS_NOT(X)                     (~MACRO_EXPRESSION(X))
#define BITS_XOR(X, Y)                  (MACRO_EXPRESSION(X) ^ MACRO_EXPRESSION(Y))
#define BITS_LEFT_SHIFT(X, Y)           (MACRO_EXPRESSION(X) << MACRO_EXPRESSION(Y))
#define BITS_RIGHT_SHIFT(X, Y)          (MACRO_EXPRESSION(X) >> MACRO_EXPRESSION(Y))

#define BITS_FLAG8(OFFSET)              BITS_LEFT_SHIFT((uint8_t)1, OFFSET)
#define BITS_FLAG16(OFFSET)             BITS_LEFT_SHIFT((uint16_t)1, OFFSET)
#define BITS_FLAG32(OFFSET)             BITS_LEFT_SHIFT((uint32_t)1, OFFSET)
#define BITS_FLAG64(OFFSET)             BITS_LEFT_SHIFT((uint64_t)1, OFFSET)

#define BITS_SET_FLAG(FLAGS, FLAG)      (FLAGS = BITS_OR(FLAGS, FLAG))
#define BITS_CLEAR_FLAG(FLAGS, FLAG)    (FLAGS = BITS_AND(FLAGS, BITS_NOT(FLAG)))
#define BITS_REVERSE_FLAG(FLAGS, FLAG)  (FLAGS = BITS_XOR(FLAGS, FLAG))
#define BITS_TEST_FLAGS(FLAGS, FLAG)    BITS_LOGIC_NOT_EQUAL(BITS_AND(FLAGS, FLAG), 0)

#endif // __BITS_H
