#if !defined(__INTERRUPT_EXCEPTIONS_H)
#define __INTERRUPT_EXCEPTIONS_H

//Reference: https://wiki.osdev.org/Exceptions

#define EXCEPTION_VEC_DIV_BY_ZERO                   0x00
#define EXCEPTION_VEC_DEBUG                         0x01
#define EXCEPTION_VEC_NON_MASKABLE_INTERRUPT        0x02
#define EXCEPTION_VEC_BREAKPOINT                    0x03
#define EXCEPTION_VEC_OVERFLOW                      0x04
#define EXCEPTION_VEC_BOUND_RANGE_EXCEEDED          0x05
#define EXCEPTION_VEC_INVALID_OPCODE                0x06
#define EXCEPTION_VEC_DEVICE_NOT_AVAILABLE          0x07
#define EXCEPTION_VEC_DOUBLE_FAULT                  0x08
#define EXCEPTION_VEC_INVALID_TSS                   0x0A
#define EXCEPTION_VEC_SEGMENT_NOT_PRESENT           0x0B
#define EXCEPTION_VEC_STACK_SEGMENT_FAULT           0x0C
#define EXCEPTION_VEC_GENERAL_PROTECTION_FAULT      0x0D
#define EXCEPTION_VEC_PAGE_FAULT                    0x0E
#define EXCEPTION_VEC_X87_FLOATING_POINT_EXCEPTION  0x10
#define EXCEPTION_VEC_ALIGNMENT_CHECK               0x11
#define EXCEPTION_VEC_MACHINE_CHECK                 0x12
#define EXCEPTION_VEC_SIMD_FLOATING_POINT_EXCEPTION 0x13
#define EXCEPTION_VEC_VIRTUALIZATION_EXCEPTION      0x14
#define EXCEPTION_VEC_CONTROL_PROTECTION_EXCEPTION  0x15
#define EXCEPTION_VEC_INJECTION_EXCEPTION           0x1C
#define EXCEPTION_VEC_VMM_COMMUNICATION_EXCEPTION   0x1D
#define EXCEPTION_VEC_SECURITY_EXCEPTION            0x1E

#endif // __INTERRUPT_EXCEPTIONS_H
