#if !defined(__MEMORY_MAPPING_H)
#define __MEMORY_MAPPING_H

#include<kit/bit.h>
#include<kit/types.h>
#include<fs/fsEntry.h>

#define MAPPING_MMAP_PROT_EXEC                  FLAG32(0)
#define MAPPING_MMAP_PROT_READ                  FLAG32(1)
#define MAPPING_MMAP_PROT_WRITE                 FLAG32(2)
#define MAPPING_MMAP_PROT_USER                  FLAG32(3)
#define MAPPING_MMAP_PROT_GROWSDOWN             FLAG32(24)
#define MAPPING_MMAP_PROT_GROWSUP               FLAG32(25)

#define MAPPING_MMAP_FLAGS_TYPE_SHARED          0x01
#define MAPPING_MMAP_FLAGS_TYPE_PRIVATE         0x02
#define MAPPING_MMAP_FLAGS_TYPE_SHARED_VALIDATE 0x03
#define MAPPING_MMAP_FLAGS_TYPE_MASK            0x0F
#define MAPPING_MMAP_FLAGS_FILE                 EMPTY_FLAGS
#define MAPPING_MMAP_FLAGS_FIXED                FLAG32(4)
#define MAPPING_MMAP_FLAGS_ANON                 FLAG32(5)
#define MAPPING_MMAP_FLAGS_ANONYMOUS            SYSCALL_MAPPING_MMAP_FLAGS_ANON
#define MAPPING_MMAP_FLAGS_GROWSDOWN            Flags32(8)
#define MAPPING_MMAP_FLAGS_DENYWRITE            FLAG32(11)
#define MAPPING_MMAP_FLAGS_EXECUTABLE           FLAG32(12)
#define MAPPING_MMAP_FLAGS_LOCKED               FLAG32(13)
#define MAPPING_MMAP_FLAGS_POPULATE             FLAG32(15)
#define MAPPING_MMAP_FLAGS_NONBLOCK             FLAG32(16)
#define MAPPING_MMAP_FLAGS_STACK                FLAG32(17)
#define MAPPING_MMAP_FLAGS_HUGETLB              FLAG32(18)
#define MAPPING_MMAP_FLAGS_SYNC                 FLAG32(19)
#define MAPPING_MMAP_FLAGS_FIXED_NOREPLACE      FLAG32(20)
#define MAPPING_MMAP_FLAGS_HUGETLB_BEGIN        26
#define MAPPING_MMAP_FLAGS_HUGETLB_END          32
#define MAPPING_MMAP_FLAGS_HUGETLB_64KB         VAL_LEFT_SHIFT((Flags32)16, SYSCALL_MAPPING_MMAP_FLAGS_HUGETLB_BEGIN)
#define MAPPING_MMAP_FLAGS_HUGETLB_512KB        VAL_LEFT_SHIFT((Flags32)19, SYSCALL_MAPPING_MMAP_FLAGS_HUGETLB_BEGIN)
#define MAPPING_MMAP_FLAGS_HUGETLB_1MB          VAL_LEFT_SHIFT((Flags32)20, SYSCALL_MAPPING_MMAP_FLAGS_HUGETLB_BEGIN)
#define MAPPING_MMAP_FLAGS_HUGETLB_2MB          VAL_LEFT_SHIFT((Flags32)21, SYSCALL_MAPPING_MMAP_FLAGS_HUGETLB_BEGIN)
#define MAPPING_MMAP_FLAGS_HUGETLB_8MB          VAL_LEFT_SHIFT((Flags32)23, SYSCALL_MAPPING_MMAP_FLAGS_HUGETLB_BEGIN)
#define MAPPING_MMAP_FLAGS_HUGETLB_16MB         VAL_LEFT_SHIFT((Flags32)24, SYSCALL_MAPPING_MMAP_FLAGS_HUGETLB_BEGIN)
#define MAPPING_MMAP_FLAGS_HUGETLB_32MB         VAL_LEFT_SHIFT((Flags32)25, SYSCALL_MAPPING_MMAP_FLAGS_HUGETLB_BEGIN)
#define MAPPING_MMAP_FLAGS_HUGETLB_256MB        VAL_LEFT_SHIFT((Flags32)28, SYSCALL_MAPPING_MMAP_FLAGS_HUGETLB_BEGIN)
#define MAPPING_MMAP_FLAGS_HUGETLB_512MB        VAL_LEFT_SHIFT((Flags32)29, SYSCALL_MAPPING_MMAP_FLAGS_HUGETLB_BEGIN)
#define MAPPING_MMAP_FLAGS_HUGETLB_1GB          VAL_LEFT_SHIFT((Flags32)30, SYSCALL_MAPPING_MMAP_FLAGS_HUGETLB_BEGIN)
#define MAPPING_MMAP_FLAGS_HUGETLB_2GB          VAL_LEFT_SHIFT((Flags32)31, SYSCALL_MAPPING_MMAP_FLAGS_HUGETLB_BEGIN)
#define MAPPING_MMAP_FLAGS_HUGETLB_16GB         VAL_LEFT_SHIFT((Flags32)34, SYSCALL_MAPPING_MMAP_FLAGS_HUGETLB_BEGIN)
#define MAPPING_MMAP_FLAGS_UNINITIALIZED        FLAG64(26)

void* mapping_mmap(void* prefer, Size length, Flags32 prot, Flags32 flags, File* file, Index64 offset);

void mapping_munmap(void* addr, Size length);

#endif // __MEMORY_MAPPING_H
