#if !defined(__SYSTEM_MEMORYLAYOUT_H)
#define __SYSTEM_MEMORYLAYOUT_H

#define DATA_UNIT_B                                 (1ull)
#define DATA_UNIT_KB                                (1ull << 10)
#define DATA_UNIT_MB                                (1ull << 20)
#define DATA_UNIT_GB                                (1ull << 30)
#define DATA_UNIT_TB                                (1ull << 40)

#define MEMORY_LAYOUT_MAX_PHYSICAL_MEMORY_SIZE      (128 * DATA_UNIT_GB)

#define MEMORY_LAYOUT_BOOT_MBR_BEGIN                0x0000000000007C00
#define MEMORY_LAYOUT_BOOT_MBR_END                  0x0000000000007E00

#define MEMORY_LAYOUT_BOOT_STACK_BOTTOM             MEMORY_LAYOUT_BOOT_MBR_BEGIN

#define MEMORY_LAYOUT_BOOT_BOOTLOADER_BEGIN         MEMORY_LAYOUT_BOOT_MBR_END
#define MEMORY_LAYOUT_BOOT_BOOTLOADER_END           0x0000000000010000

#define MEMORY_LAYOUT_BOOT_MEMALLOC_BEGIN           MEMORY_LAYOUT_BOOT_BOOTLOADER_END
#define MEMORY_LAYOUT_BOOT_MEMALLOC_END             0x0000000000040000

#define MEMORY_LAYOUT_KERNEL_LOAD_BEGIN             0x0000000000100000
#define MEMORY_LAYOUT_KERNEL_STACK_BOTTOM           0x0000000000080000

#define MEMORY_LAYOUT_KERNEL_BEGIN                  (1ull * DATA_UNIT_TB)
#define MEMORY_LAYOUT_USER_STACK_BOTTOM             MEMORY_LAYOUT_KERNEL_BEGIN

#define MEMORY_LAYOUT_KERNEL_HEAP_BEGIN             0xFFFFFE0000000000

#define MEMORY_LAYOUT_KERNEL_IDENTICAL_MEMORY_BEGIN 0xFFFFFF0000000000
#define MEMORY_LAYOUT_KERNEL_IDENTICAL_MEMORY_END   (MEMORY_LAYOUT_KERNEL_IDENTICAL_MEMORY_BEGIN + MEMORY_LAYOUT_MAX_PHYSICAL_MEMORY_SIZE)

#define MEMORY_LAYOUT_KERNEL_KERNEL_TEXT_BEGIN      0xFFFFFFFFC0000000
#define MEMORY_LAYOUT_KERNEL_KERNEL_TEXT_END        0xFFFFFFFFE0000000

#endif // __SYSTEM_MEMORYLAYOUT_H
