#include<interrupt/IDT.h>
#include<interrupt/ISR.h>
#include<kit/macro.h>
#include<kit/types.h>

extern void (*ISRhandlers[256]) (uint8_t vec, InterruptFrame* interruptFrame);

#define INTERRUPT_STUB_NAME(__NUMBER) MACRO_CONCENTRATE2(interruptStub_, __NUMBER)

#define INTERRUPT_STUB(__NUMBER)                                        \
__attribute__((interrupt, target("general-regs-only")))                 \
void INTERRUPT_STUB_NAME(__NUMBER) (InterruptFrame* interruptFrame) {   \
    uint8_t vec;                                                        \
    asm volatile(                                                       \
    "mov $" MACRO_STR(__NUMBER) ", %0\n"                                \
    : "=g"(vec)                                                         \
    );                                                                  \
    ISRhandlers[vec](vec, interruptFrame);                              \
    EOI();                                                              \
}

INTERRUPT_STUB(0x00) INTERRUPT_STUB(0x01) INTERRUPT_STUB(0x02) INTERRUPT_STUB(0x03)
INTERRUPT_STUB(0x04) INTERRUPT_STUB(0x05) INTERRUPT_STUB(0x06) INTERRUPT_STUB(0x07)
INTERRUPT_STUB(0x08) INTERRUPT_STUB(0x09) INTERRUPT_STUB(0x0A) INTERRUPT_STUB(0x0B)
INTERRUPT_STUB(0x0C) INTERRUPT_STUB(0x0D) INTERRUPT_STUB(0x0E) INTERRUPT_STUB(0x0F)

INTERRUPT_STUB(0x10) INTERRUPT_STUB(0x11) INTERRUPT_STUB(0x12) INTERRUPT_STUB(0x13)
INTERRUPT_STUB(0x14) INTERRUPT_STUB(0x15) INTERRUPT_STUB(0x16) INTERRUPT_STUB(0x17)
INTERRUPT_STUB(0x18) INTERRUPT_STUB(0x19) INTERRUPT_STUB(0x1A) INTERRUPT_STUB(0x1B)
INTERRUPT_STUB(0x1C) INTERRUPT_STUB(0x1D) INTERRUPT_STUB(0x1E) INTERRUPT_STUB(0x1F)

INTERRUPT_STUB(0x20) INTERRUPT_STUB(0x21) INTERRUPT_STUB(0x22) INTERRUPT_STUB(0x23)
INTERRUPT_STUB(0x24) INTERRUPT_STUB(0x25) INTERRUPT_STUB(0x26) INTERRUPT_STUB(0x27)
INTERRUPT_STUB(0x28) INTERRUPT_STUB(0x29) INTERRUPT_STUB(0x2A) INTERRUPT_STUB(0x2B)
INTERRUPT_STUB(0x2C) INTERRUPT_STUB(0x2D) INTERRUPT_STUB(0x2E) INTERRUPT_STUB(0x2F)

INTERRUPT_STUB(0x30) INTERRUPT_STUB(0x31) INTERRUPT_STUB(0x32) INTERRUPT_STUB(0x33)
INTERRUPT_STUB(0x34) INTERRUPT_STUB(0x35) INTERRUPT_STUB(0x36) INTERRUPT_STUB(0x37)
INTERRUPT_STUB(0x38) INTERRUPT_STUB(0x39) INTERRUPT_STUB(0x3A) INTERRUPT_STUB(0x3B)
INTERRUPT_STUB(0x3C) INTERRUPT_STUB(0x3D) INTERRUPT_STUB(0x3E) INTERRUPT_STUB(0x3F)

INTERRUPT_STUB(0x40) INTERRUPT_STUB(0x41) INTERRUPT_STUB(0x42) INTERRUPT_STUB(0x43)
INTERRUPT_STUB(0x44) INTERRUPT_STUB(0x45) INTERRUPT_STUB(0x46) INTERRUPT_STUB(0x47)
INTERRUPT_STUB(0x48) INTERRUPT_STUB(0x49) INTERRUPT_STUB(0x4A) INTERRUPT_STUB(0x4B)
INTERRUPT_STUB(0x4C) INTERRUPT_STUB(0x4D) INTERRUPT_STUB(0x4E) INTERRUPT_STUB(0x4F)

INTERRUPT_STUB(0x50) INTERRUPT_STUB(0x51) INTERRUPT_STUB(0x52) INTERRUPT_STUB(0x53)
INTERRUPT_STUB(0x54) INTERRUPT_STUB(0x55) INTERRUPT_STUB(0x56) INTERRUPT_STUB(0x57)
INTERRUPT_STUB(0x58) INTERRUPT_STUB(0x59) INTERRUPT_STUB(0x5A) INTERRUPT_STUB(0x5B)
INTERRUPT_STUB(0x5C) INTERRUPT_STUB(0x5D) INTERRUPT_STUB(0x5E) INTERRUPT_STUB(0x5F)

INTERRUPT_STUB(0x60) INTERRUPT_STUB(0x61) INTERRUPT_STUB(0x62) INTERRUPT_STUB(0x63)
INTERRUPT_STUB(0x64) INTERRUPT_STUB(0x65) INTERRUPT_STUB(0x66) INTERRUPT_STUB(0x67)
INTERRUPT_STUB(0x68) INTERRUPT_STUB(0x69) INTERRUPT_STUB(0x6A) INTERRUPT_STUB(0x6B)
INTERRUPT_STUB(0x6C) INTERRUPT_STUB(0x6D) INTERRUPT_STUB(0x6E) INTERRUPT_STUB(0x6F)

INTERRUPT_STUB(0x70) INTERRUPT_STUB(0x71) INTERRUPT_STUB(0x72) INTERRUPT_STUB(0x73)
INTERRUPT_STUB(0x74) INTERRUPT_STUB(0x75) INTERRUPT_STUB(0x76) INTERRUPT_STUB(0x77)
INTERRUPT_STUB(0x78) INTERRUPT_STUB(0x79) INTERRUPT_STUB(0x7A) INTERRUPT_STUB(0x7B)
INTERRUPT_STUB(0x7C) INTERRUPT_STUB(0x7D) INTERRUPT_STUB(0x7E) INTERRUPT_STUB(0x7F)

INTERRUPT_STUB(0x80) INTERRUPT_STUB(0x81) INTERRUPT_STUB(0x82) INTERRUPT_STUB(0x83)
INTERRUPT_STUB(0x84) INTERRUPT_STUB(0x85) INTERRUPT_STUB(0x86) INTERRUPT_STUB(0x87)
INTERRUPT_STUB(0x88) INTERRUPT_STUB(0x89) INTERRUPT_STUB(0x8A) INTERRUPT_STUB(0x8B)
INTERRUPT_STUB(0x8C) INTERRUPT_STUB(0x8D) INTERRUPT_STUB(0x8E) INTERRUPT_STUB(0x8F)

INTERRUPT_STUB(0x90) INTERRUPT_STUB(0x91) INTERRUPT_STUB(0x92) INTERRUPT_STUB(0x93)
INTERRUPT_STUB(0x94) INTERRUPT_STUB(0x95) INTERRUPT_STUB(0x96) INTERRUPT_STUB(0x97)
INTERRUPT_STUB(0x98) INTERRUPT_STUB(0x99) INTERRUPT_STUB(0x9A) INTERRUPT_STUB(0x9B)
INTERRUPT_STUB(0x9C) INTERRUPT_STUB(0x9D) INTERRUPT_STUB(0x9E) INTERRUPT_STUB(0x9F)

INTERRUPT_STUB(0xA0) INTERRUPT_STUB(0xA1) INTERRUPT_STUB(0xA2) INTERRUPT_STUB(0xA3)
INTERRUPT_STUB(0xA4) INTERRUPT_STUB(0xA5) INTERRUPT_STUB(0xA6) INTERRUPT_STUB(0xA7)
INTERRUPT_STUB(0xA8) INTERRUPT_STUB(0xA9) INTERRUPT_STUB(0xAA) INTERRUPT_STUB(0xAB)
INTERRUPT_STUB(0xAC) INTERRUPT_STUB(0xAD) INTERRUPT_STUB(0xAE) INTERRUPT_STUB(0xAF)

INTERRUPT_STUB(0xB0) INTERRUPT_STUB(0xB1) INTERRUPT_STUB(0xB2) INTERRUPT_STUB(0xB3)
INTERRUPT_STUB(0xB4) INTERRUPT_STUB(0xB5) INTERRUPT_STUB(0xB6) INTERRUPT_STUB(0xB7)
INTERRUPT_STUB(0xB8) INTERRUPT_STUB(0xB9) INTERRUPT_STUB(0xBA) INTERRUPT_STUB(0xBB)
INTERRUPT_STUB(0xBC) INTERRUPT_STUB(0xBD) INTERRUPT_STUB(0xBE) INTERRUPT_STUB(0xBF)

INTERRUPT_STUB(0xC0) INTERRUPT_STUB(0xC1) INTERRUPT_STUB(0xC2) INTERRUPT_STUB(0xC3)
INTERRUPT_STUB(0xC4) INTERRUPT_STUB(0xC5) INTERRUPT_STUB(0xC6) INTERRUPT_STUB(0xC7)
INTERRUPT_STUB(0xC8) INTERRUPT_STUB(0xC9) INTERRUPT_STUB(0xCA) INTERRUPT_STUB(0xCB)
INTERRUPT_STUB(0xCC) INTERRUPT_STUB(0xCD) INTERRUPT_STUB(0xCE) INTERRUPT_STUB(0xCF)

INTERRUPT_STUB(0xD0) INTERRUPT_STUB(0xD1) INTERRUPT_STUB(0xD2) INTERRUPT_STUB(0xD3)
INTERRUPT_STUB(0xD4) INTERRUPT_STUB(0xD5) INTERRUPT_STUB(0xD6) INTERRUPT_STUB(0xD7)
INTERRUPT_STUB(0xD8) INTERRUPT_STUB(0xD9) INTERRUPT_STUB(0xDA) INTERRUPT_STUB(0xDB)
INTERRUPT_STUB(0xDC) INTERRUPT_STUB(0xDD) INTERRUPT_STUB(0xDE) INTERRUPT_STUB(0xDF)

INTERRUPT_STUB(0xE0) INTERRUPT_STUB(0xE1) INTERRUPT_STUB(0xE2) INTERRUPT_STUB(0xE3)
INTERRUPT_STUB(0xE4) INTERRUPT_STUB(0xE5) INTERRUPT_STUB(0xE6) INTERRUPT_STUB(0xE7)
INTERRUPT_STUB(0xE8) INTERRUPT_STUB(0xE9) INTERRUPT_STUB(0xEA) INTERRUPT_STUB(0xEB)
INTERRUPT_STUB(0xEC) INTERRUPT_STUB(0xED) INTERRUPT_STUB(0xEE) INTERRUPT_STUB(0xEF)

INTERRUPT_STUB(0xF0) INTERRUPT_STUB(0xF1) INTERRUPT_STUB(0xF2) INTERRUPT_STUB(0xF3)
INTERRUPT_STUB(0xF4) INTERRUPT_STUB(0xF5) INTERRUPT_STUB(0xF6) INTERRUPT_STUB(0xF7)
INTERRUPT_STUB(0xF8) INTERRUPT_STUB(0xF9) INTERRUPT_STUB(0xFA) INTERRUPT_STUB(0xFB)
INTERRUPT_STUB(0xFC) INTERRUPT_STUB(0xFD) INTERRUPT_STUB(0xFE) INTERRUPT_STUB(0xFF)

void (*stubs[256])(InterruptFrame* interruptFrame) = {
    INTERRUPT_STUB_NAME(0x00), INTERRUPT_STUB_NAME(0x01), INTERRUPT_STUB_NAME(0x02), INTERRUPT_STUB_NAME(0x03),
    INTERRUPT_STUB_NAME(0x04), INTERRUPT_STUB_NAME(0x05), INTERRUPT_STUB_NAME(0x06), INTERRUPT_STUB_NAME(0x07),
    INTERRUPT_STUB_NAME(0x08), INTERRUPT_STUB_NAME(0x09), INTERRUPT_STUB_NAME(0x0A), INTERRUPT_STUB_NAME(0x0B),
    INTERRUPT_STUB_NAME(0x0C), INTERRUPT_STUB_NAME(0x0D), INTERRUPT_STUB_NAME(0x0E), INTERRUPT_STUB_NAME(0x0F),

    INTERRUPT_STUB_NAME(0x10), INTERRUPT_STUB_NAME(0x11), INTERRUPT_STUB_NAME(0x12), INTERRUPT_STUB_NAME(0x13),
    INTERRUPT_STUB_NAME(0x14), INTERRUPT_STUB_NAME(0x15), INTERRUPT_STUB_NAME(0x16), INTERRUPT_STUB_NAME(0x17),
    INTERRUPT_STUB_NAME(0x18), INTERRUPT_STUB_NAME(0x19), INTERRUPT_STUB_NAME(0x1A), INTERRUPT_STUB_NAME(0x1B),
    INTERRUPT_STUB_NAME(0x1C), INTERRUPT_STUB_NAME(0x1D), INTERRUPT_STUB_NAME(0x1E), INTERRUPT_STUB_NAME(0x1F),

    INTERRUPT_STUB_NAME(0x20), INTERRUPT_STUB_NAME(0x21), INTERRUPT_STUB_NAME(0x22), INTERRUPT_STUB_NAME(0x23),
    INTERRUPT_STUB_NAME(0x24), INTERRUPT_STUB_NAME(0x25), INTERRUPT_STUB_NAME(0x26), INTERRUPT_STUB_NAME(0x27),
    INTERRUPT_STUB_NAME(0x28), INTERRUPT_STUB_NAME(0x29), INTERRUPT_STUB_NAME(0x2A), INTERRUPT_STUB_NAME(0x2B),
    INTERRUPT_STUB_NAME(0x2C), INTERRUPT_STUB_NAME(0x2D), INTERRUPT_STUB_NAME(0x2E), INTERRUPT_STUB_NAME(0x2F),

    INTERRUPT_STUB_NAME(0x30), INTERRUPT_STUB_NAME(0x31), INTERRUPT_STUB_NAME(0x32), INTERRUPT_STUB_NAME(0x33),
    INTERRUPT_STUB_NAME(0x34), INTERRUPT_STUB_NAME(0x35), INTERRUPT_STUB_NAME(0x36), INTERRUPT_STUB_NAME(0x37),
    INTERRUPT_STUB_NAME(0x38), INTERRUPT_STUB_NAME(0x39), INTERRUPT_STUB_NAME(0x3A), INTERRUPT_STUB_NAME(0x3B),
    INTERRUPT_STUB_NAME(0x3C), INTERRUPT_STUB_NAME(0x3D), INTERRUPT_STUB_NAME(0x3E), INTERRUPT_STUB_NAME(0x3F),

    INTERRUPT_STUB_NAME(0x40), INTERRUPT_STUB_NAME(0x41), INTERRUPT_STUB_NAME(0x42), INTERRUPT_STUB_NAME(0x43),
    INTERRUPT_STUB_NAME(0x44), INTERRUPT_STUB_NAME(0x45), INTERRUPT_STUB_NAME(0x46), INTERRUPT_STUB_NAME(0x47),
    INTERRUPT_STUB_NAME(0x48), INTERRUPT_STUB_NAME(0x49), INTERRUPT_STUB_NAME(0x4A), INTERRUPT_STUB_NAME(0x4B),
    INTERRUPT_STUB_NAME(0x4C), INTERRUPT_STUB_NAME(0x4D), INTERRUPT_STUB_NAME(0x4E), INTERRUPT_STUB_NAME(0x4F),

    INTERRUPT_STUB_NAME(0x50), INTERRUPT_STUB_NAME(0x51), INTERRUPT_STUB_NAME(0x52), INTERRUPT_STUB_NAME(0x53),
    INTERRUPT_STUB_NAME(0x54), INTERRUPT_STUB_NAME(0x55), INTERRUPT_STUB_NAME(0x56), INTERRUPT_STUB_NAME(0x57),
    INTERRUPT_STUB_NAME(0x58), INTERRUPT_STUB_NAME(0x59), INTERRUPT_STUB_NAME(0x5A), INTERRUPT_STUB_NAME(0x5B),
    INTERRUPT_STUB_NAME(0x5C), INTERRUPT_STUB_NAME(0x5D), INTERRUPT_STUB_NAME(0x5E), INTERRUPT_STUB_NAME(0x5F),

    INTERRUPT_STUB_NAME(0x60), INTERRUPT_STUB_NAME(0x61), INTERRUPT_STUB_NAME(0x62), INTERRUPT_STUB_NAME(0x63),
    INTERRUPT_STUB_NAME(0x64), INTERRUPT_STUB_NAME(0x65), INTERRUPT_STUB_NAME(0x66), INTERRUPT_STUB_NAME(0x67),
    INTERRUPT_STUB_NAME(0x68), INTERRUPT_STUB_NAME(0x69), INTERRUPT_STUB_NAME(0x6A), INTERRUPT_STUB_NAME(0x6B),
    INTERRUPT_STUB_NAME(0x6C), INTERRUPT_STUB_NAME(0x6D), INTERRUPT_STUB_NAME(0x6E), INTERRUPT_STUB_NAME(0x6F),

    INTERRUPT_STUB_NAME(0x70), INTERRUPT_STUB_NAME(0x71), INTERRUPT_STUB_NAME(0x72), INTERRUPT_STUB_NAME(0x73),
    INTERRUPT_STUB_NAME(0x74), INTERRUPT_STUB_NAME(0x75), INTERRUPT_STUB_NAME(0x76), INTERRUPT_STUB_NAME(0x77),
    INTERRUPT_STUB_NAME(0x78), INTERRUPT_STUB_NAME(0x79), INTERRUPT_STUB_NAME(0x7A), INTERRUPT_STUB_NAME(0x7B),
    INTERRUPT_STUB_NAME(0x7C), INTERRUPT_STUB_NAME(0x7D), INTERRUPT_STUB_NAME(0x7E), INTERRUPT_STUB_NAME(0x7F),

    INTERRUPT_STUB_NAME(0x80), INTERRUPT_STUB_NAME(0x81), INTERRUPT_STUB_NAME(0x82), INTERRUPT_STUB_NAME(0x83),
    INTERRUPT_STUB_NAME(0x84), INTERRUPT_STUB_NAME(0x85), INTERRUPT_STUB_NAME(0x86), INTERRUPT_STUB_NAME(0x87),
    INTERRUPT_STUB_NAME(0x88), INTERRUPT_STUB_NAME(0x89), INTERRUPT_STUB_NAME(0x8A), INTERRUPT_STUB_NAME(0x8B),
    INTERRUPT_STUB_NAME(0x8C), INTERRUPT_STUB_NAME(0x8D), INTERRUPT_STUB_NAME(0x8E), INTERRUPT_STUB_NAME(0x8F),

    INTERRUPT_STUB_NAME(0x90), INTERRUPT_STUB_NAME(0x91), INTERRUPT_STUB_NAME(0x92), INTERRUPT_STUB_NAME(0x93),
    INTERRUPT_STUB_NAME(0x94), INTERRUPT_STUB_NAME(0x95), INTERRUPT_STUB_NAME(0x96), INTERRUPT_STUB_NAME(0x97),
    INTERRUPT_STUB_NAME(0x98), INTERRUPT_STUB_NAME(0x99), INTERRUPT_STUB_NAME(0x9A), INTERRUPT_STUB_NAME(0x9B),
    INTERRUPT_STUB_NAME(0x9C), INTERRUPT_STUB_NAME(0x9D), INTERRUPT_STUB_NAME(0x9E), INTERRUPT_STUB_NAME(0x9F),

    INTERRUPT_STUB_NAME(0xA0), INTERRUPT_STUB_NAME(0xA1), INTERRUPT_STUB_NAME(0xA2), INTERRUPT_STUB_NAME(0xA3),
    INTERRUPT_STUB_NAME(0xA4), INTERRUPT_STUB_NAME(0xA5), INTERRUPT_STUB_NAME(0xA6), INTERRUPT_STUB_NAME(0xA7),
    INTERRUPT_STUB_NAME(0xA8), INTERRUPT_STUB_NAME(0xA9), INTERRUPT_STUB_NAME(0xAA), INTERRUPT_STUB_NAME(0xAB),
    INTERRUPT_STUB_NAME(0xAC), INTERRUPT_STUB_NAME(0xAD), INTERRUPT_STUB_NAME(0xAE), INTERRUPT_STUB_NAME(0xAF),

    INTERRUPT_STUB_NAME(0xB0), INTERRUPT_STUB_NAME(0xB1), INTERRUPT_STUB_NAME(0xB2), INTERRUPT_STUB_NAME(0xB3),
    INTERRUPT_STUB_NAME(0xB4), INTERRUPT_STUB_NAME(0xB5), INTERRUPT_STUB_NAME(0xB6), INTERRUPT_STUB_NAME(0xB7),
    INTERRUPT_STUB_NAME(0xB8), INTERRUPT_STUB_NAME(0xB9), INTERRUPT_STUB_NAME(0xBA), INTERRUPT_STUB_NAME(0xBB),
    INTERRUPT_STUB_NAME(0xBC), INTERRUPT_STUB_NAME(0xBD), INTERRUPT_STUB_NAME(0xBE), INTERRUPT_STUB_NAME(0xBF),

    INTERRUPT_STUB_NAME(0xC0), INTERRUPT_STUB_NAME(0xC1), INTERRUPT_STUB_NAME(0xC2), INTERRUPT_STUB_NAME(0xC3),
    INTERRUPT_STUB_NAME(0xC4), INTERRUPT_STUB_NAME(0xC5), INTERRUPT_STUB_NAME(0xC6), INTERRUPT_STUB_NAME(0xC7),
    INTERRUPT_STUB_NAME(0xC8), INTERRUPT_STUB_NAME(0xC9), INTERRUPT_STUB_NAME(0xCA), INTERRUPT_STUB_NAME(0xCB),
    INTERRUPT_STUB_NAME(0xCC), INTERRUPT_STUB_NAME(0xCD), INTERRUPT_STUB_NAME(0xCE), INTERRUPT_STUB_NAME(0xCF),

    INTERRUPT_STUB_NAME(0xD0), INTERRUPT_STUB_NAME(0xD1), INTERRUPT_STUB_NAME(0xD2), INTERRUPT_STUB_NAME(0xD3),
    INTERRUPT_STUB_NAME(0xD4), INTERRUPT_STUB_NAME(0xD5), INTERRUPT_STUB_NAME(0xD6), INTERRUPT_STUB_NAME(0xD7),
    INTERRUPT_STUB_NAME(0xD8), INTERRUPT_STUB_NAME(0xD9), INTERRUPT_STUB_NAME(0xDA), INTERRUPT_STUB_NAME(0xDB),
    INTERRUPT_STUB_NAME(0xDC), INTERRUPT_STUB_NAME(0xDD), INTERRUPT_STUB_NAME(0xDE), INTERRUPT_STUB_NAME(0xDF),

    INTERRUPT_STUB_NAME(0xE0), INTERRUPT_STUB_NAME(0xE1), INTERRUPT_STUB_NAME(0xE2), INTERRUPT_STUB_NAME(0xE3),
    INTERRUPT_STUB_NAME(0xE4), INTERRUPT_STUB_NAME(0xE5), INTERRUPT_STUB_NAME(0xE6), INTERRUPT_STUB_NAME(0xE7),
    INTERRUPT_STUB_NAME(0xE8), INTERRUPT_STUB_NAME(0xE9), INTERRUPT_STUB_NAME(0xEA), INTERRUPT_STUB_NAME(0xEB),
    INTERRUPT_STUB_NAME(0xEC), INTERRUPT_STUB_NAME(0xED), INTERRUPT_STUB_NAME(0xEE), INTERRUPT_STUB_NAME(0xEF),

    INTERRUPT_STUB_NAME(0xF0), INTERRUPT_STUB_NAME(0xF1), INTERRUPT_STUB_NAME(0xF2), INTERRUPT_STUB_NAME(0xF3),
    INTERRUPT_STUB_NAME(0xF4), INTERRUPT_STUB_NAME(0xF5), INTERRUPT_STUB_NAME(0xF6), INTERRUPT_STUB_NAME(0xF7),
    INTERRUPT_STUB_NAME(0xF8), INTERRUPT_STUB_NAME(0xF9), INTERRUPT_STUB_NAME(0xFA), INTERRUPT_STUB_NAME(0xFB),
    INTERRUPT_STUB_NAME(0xFC), INTERRUPT_STUB_NAME(0xFD), INTERRUPT_STUB_NAME(0xFE), INTERRUPT_STUB_NAME(0xFF)
};